CREATE DATABASE MYDATABASE;
GO
USE MYDATABASE;

CREATE TABLE USER (
    USER_ID INT PRIMARY KEY IDENTITY(1,1),
    USER_NAME VARCHAR(50) NOT NULL,
    USER_SURNAME VARCHAR(50) NOT NULL,
    USER_EMAIL VARCHAR(100) UNIQUE NOT NULL,
    USER_PHONENUMBER VARCHAR(10) UNIQUE,
    USER_ADDRESS VARCHAR(100),
    USER_IDNUMBER INT NOT NULL
);
GO

/*
comment added
*/
