CREATE DATABASE MYDATABASE;
-- GO -- Commented out for SQLFluff (if needed, uncomment for SQL Server tools)
USE MYDATABASE;

CREATE TABLE USERS (
    USER_ID INT PRIMARY KEY IDENTITY(1,1),
    USER_NAME VARCHAR(50) NOT NULL,
    USER_SURNAME VARCHAR(50) NOT NULL,
    USER_EMAIL VARCHAR(100) UNIQUE NOT NULL,
    USER_PHONENUMBER VARCHAR(10) UNIQUE,
    USER_ADDRESS VARCHAR(100),
    USER_IDNUMBER INT NOT NULL
);
-- GO -- Commented out for SQLFluff (if needed, uncomment for SQL Server tools)

-- Comment added
