name: SQL Deployment Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      DB_NAME:
        required: true
        type: string
      sql-user:
        description: "SQL username for authentication"
        required: false
        default: "Auto_user"
        type: string
    secrets:
      SQL_SERVER:
        required: true
      SQL_PASSWORD:
        required: true

jobs:
  deploy:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment == 'production' && 'Need-Siphenathi-Approval' || '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for consistency

      - name: Add Microsoft repository for SQL Server tools
        run: |
          echo "Adding Microsoft repository for SQL Server tools..."
          sudo apt-get update
          sudo apt-get install -y curl gnupg  # Install curl and gnupg for repo setup
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -  # Add Microsoft key
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list  # Add Microsoft repo
          sudo apt-get update  # Update package list

      - name: Install SQL Server client
        run: |
          echo "Installing SQL Server client (sqlcmd)..."
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev  # Install sqlcmd and ODBC driver, accepting EULA

      - name: Add SQL Server tools to PATH
        run: |
          echo "Adding SQL Server tools to PATH..."
          echo "/opt/mssql-tools/bin" >> $GITHUB_PATH  # Ensure sqlcmd is available in PATH

      - name: Test Connection to SQL Server
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USER: ${{ inputs.sql-user }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          DB_NAME: ${{ inputs.DB_NAME }}
        run: |
          echo "Testing connection to ${{ inputs.environment }} ($SQL_SERVER)..."
          {
            sqlcmd -S "$SQL_SERVER" -U "$SQL_USER" -P "$SQL_PASSWORD" -d "$DB_NAME" -C -Q "SELECT @@VERSION" -l 60
            echo "Connection to ${{ inputs.environment }} successful."
          } || {
            echo "::error::Connection to ${{ inputs.environment }} failed! Check server, user, or password."
            exit 1
          }

      - name: ${{ inputs.environment }}
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USER: ${{ inputs.sql-user }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          DB_NAME: ${{ inputs.DB_NAME }}
        run: |
          echo "Deploying to ${{ inputs.environment }} ($SQL_SERVER) on database $DB_NAME..."
          {
            # Assuming the script is designed to work with the specified database
            sqlcmd -S "$SQL_SERVER" -U "$SQL_USER" -P "$SQL_PASSWORD" -d "$DB_NAME" -C -i "DatabaseAdministration/SQLStatements/ProductionAndDeploymentProject.sql" -l 60
            echo "Deployment to ${{ inputs.environment }} successful."
          } || {
            echo "::error::Deployment to ${{ inputs.environment }} failed!"
            exit 1
          }

      - name: Verify Deployment
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USER: ${{ inputs.sql-user }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          DB_NAME: ${{ inputs.DB_NAME }}
        run: |
          echo "Verifying deployment in ${{ inputs.environment }}..."
          {
            sqlcmd -S "$SQL_SERVER" -U "$SQL_USER" -P "$SQL_PASSWORD" -d "$DB_NAME" -C -Q "SELECT * FROM [dbo].[user]" -l 60
            echo "Verification successful in ${{ inputs.environment }}."
          } || {
            echo "::error::Verification failed in ${{ inputs.environment }}!"
            exit 1
          }
